#ifndef WIKIPATH_GRAPH_HEADER_H_INCLUDED
#define WIKIPATH_GRAPH_HEADER_H_INCLUDED

#include <stdint.h>

namespace wikipath {

const uint32_t graph_header_magic_value = 0x57494b49u;  // WIKI

enum GraphHeaderFields {
    GRAPH_HEADER_MAGIC,
    GRAPH_HEADER_FILE_SIZE,
    GRAPH_HEADER_VERTEX_COUNT,
    GRAPH_HEADER_EDGE_COUNT,
    GRAPH_HEADER_FORWARD_EDGE_INDEX_OFFSET,
    GRAPH_HEADER_BACKWARD_EDGE_INDEX_OFFSET,
    GRAPH_HEADER_FIELD_COUNT
};

}  // namespace wikipath

#endif  // ndef WIKIPATH_GRAPH_HEADER_H_INCLUDED
